python -u run.py \
--task_name classification \
--is_training 1 \
--root_path ./all_datasets/EV/ \
--data UEA \
--model_id EV \
--model ModernTCN \
--random_seed 2025 \
--ffn_ratio 2 \
--patch_size 128 \
--patch_stride 16 \
--num_blocks 3 \
--large_size 91 \
--small_size 5 \
--dims 64 \
--head_dropout 0.05 \
--dropout 0.4 \
--class_dropout 0.2 \
--threshold 0.4 \
--itr 1 \
--learning_rate 0.0005 \
--batch_size 64 \
--train_epochs 100 \
--patience 50 \
--des Exp \
--use_multi_scale True \
--do_predict